version: '2'

services:
  apache-php-1:
    image: php:7.0-apache
    container_name: apache-php-1
    volumes:
      - ./sample-server/src/index.php:/var/www/html/index.php
    networks:
      - haproxy

  apache-php-2:
    image: php:7.0-apache
    container_name: apache-php-2
    volumes:
      - ./sample-server/src/index.php:/var/www/html/index.php
    networks:
      - haproxy
  
  apache-php-3:
    image: php:7.0-apache
    container_name: apache-php-3
    volumes:
      - ./sample-server/src/index.php:/var/www/html/index.php
    networks:
      - haproxy
    
  apache-php-4:
    image: php:7.0-apache
    container_name: apache-php-4
    volumes:
      - ./sample-server/src/index.php:/var/www/html/index.php
    networks:
      - haproxy

  haproxy:
    image: bitnami/haproxy
    user: root
    volumes:
      - ./configs/haproxy.cfg:/bitnami/haproxy/conf/haproxy.cfg
    container_name: haproxy
    networks:
      - haproxy
    ports: 
      - '0.0.0.0::80'
    depends_on: 
      - apache-php-1
      - apache-php-2
      - apache-php-3
      - apache-php-4

networks:
  haproxy:
    driver: bridge
