version: '2'

services:
  apache-php-1:
    build: ./configs/sample-server
    container_name: apache-php-1
    networks:
      - haproxy

  apache-php-2:
    build: ./configs/sample-server
    container_name: apache-php-2
    networks:
      - haproxy
  
  apache-php-3:
    build: ./configs/sample-server
    container_name: apache-php-3
    networks:
      - haproxy
    
  apache-php-4:
    build: ./configs/sample-server
    container_name: apache-php-4
    networks:
      - haproxy

  haproxy:
    image: bitnami/haproxy
    user: root
    volumes:
      - ./configs/haproxy.cfg:/bitnami/haproxy/conf/haproxy.cfg
    container_name: haproxy
    networks:
      - haproxy
    ports: 
      - '0.0.0.0::80'
    depends_on: 
      - apache-php-1
      - apache-php-2
      - apache-php-3
      - apache-php-4

networks:
  haproxy:
    driver: bridge
