version: '2'

services:
  python-flask-1:
    build: ./configs/sample-server
    container_name: python-flask-1
    networks:
      - haproxy

  python-flask-2:
    build: ./configs/sample-server
    container_name: python-flask-2
    networks:
      - haproxy
  
  python-flask-3:
    build: ./configs/sample-server
    container_name: python-flask-3
    networks:
      - haproxy
    
  python-flask-4:
    build: ./configs/sample-server
    container_name: python-flask-4
    networks:
      - haproxy

  haproxy:
    image: bitnami/haproxy
    user: root
    volumes:
      - ./configs/haproxy.cfg:/bitnami/haproxy/conf/haproxy.cfg
    container_name: haproxy
    networks:
      - haproxy
    ports: 
      - '0.0.0.0::80'
    depends_on: 
      - python-flask-1
      - python-flask-2
      - python-flask-3
      - python-flask-4

networks:
  haproxy:
    driver: bridge
